config/routes.rb
Rails.application.routes.draw do
  resources :item

  root 'item#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/item_controller.rb
require 'open-uri'
require 'json'
require 'date'

class ItemController < ApplicationController
  @@iteration = 0
  def index
    num_items = 0 + 30 * @@iteration
    @items = []
    list = JSON.parse(open("https://hacker-news.firebaseio.com/v0/topstories.json").read)
    30.times do |i|
      num_items += 1
      content = {}
      item = JSON.parse(open("https://hacker-news.firebaseio.com/v0/item/" + list[num_items-1].to_s + ".json").read)
      content['id'] = list[num_items-1]
      content['comment_link'] = 'https://news.ycombinator.com/item?id=' + content['id'].to_s
      content['ranking'] = num_items
      content['title'] = item['title']
      content['url'] = item['url']
      if content['url'] == nil
        content['host'] = ''
        content['host_search'] = ''
      else
        host = URI(item['url']).host
        if host.start_with?('www.')
          host = host[4..-1]
        end
        content['host'] = '(' + host.to_s + ')'
        content['host_search'] = "https://news.ycombinator.com/from?site=" + host.to_s
      end
      if item['score'] <= 1
        content['score'] = item['score'].to_s + ' point'
      else
        content['score'] = item['score'].to_s + ' points'
      end
      content['by'] = item['by']
      content['by_link'] = 'https://news.ycombinator.com/user?id=' + item['by']
      time_elapsed = Time.at(Time.now.to_i - item['time']).utc.strftime("%H%M%S").to_i.to_s
      time_elapsed_length = time_elapsed.length
      time_display = ''
      if time_elapsed.length == 6
        time_display = time_elapsed[0..1] + ' hours'
      elsif time_elapsed.length == 5
        if time_elapsed[0] == '1'
          time_display = time_elapsed[0] + ' hour'
        else
          time_display = time_elapsed[0] + ' hours'
        end
      elsif time_elapsed.length == 4
        time_display = time_elapsed[0..1] + ' minutes'
      elsif time_elapsed.length == 3
        if time_elapsed[0] == '1'
          time_display = time_elapsed[0] + ' minute'
        else
          time_display = time_elapsed[0] + ' minutes'
        end
      elsif time_elapsed.length == 2
        time_display = time_elapsed[0..1] + ' seconds'
      else time_elapsed.length == 1
        if time_elapsed[0] == '1'
          time_display = time_elapsed[0] + ' second'
        else
          time_display = time_elapsed[0] + ' seconds'
        end
      end
      content['time'] = time_display
      if item['kids'] == nil
        content['comment'] = 'discuss'
      else
        content['comment'] = item['kids'].length.to_s + ' comments'
      end
      @items.push(content)
    end
    respond_to do |format|
      format.html
      format.xml { render :xml => @items.to_xml }
    end
    @@iteration += 1
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/item/index.html.erb
<div class="container">
  <div class="top">
    <div class="left">
      <div class="title">
        <a href=".">
          <%=image_tag('y18.gif')%>
        </a>
      </div>
      <div class="menu">
        <b>Hacker News</b>
        <div class="category">
          <a href="https://news.ycombinator.com/newest">new</a> |
          <a href="https://news.ycombinator.com/newcomments">comments</a> |
          <a href="https://news.ycombinator.com/show">show</a> |
          <a href="https://news.ycombinator.com/ask">ask</a> |
          <a href="https://news.ycombinator.com/jobs">jobs</a> |
          <a href="https://news.ycombinator.com/submit">submit</a>
        </div>
      </div>
    </div>
    <div class="login">
      <a href="#">login</a>
    </div>
  </div>
  <div class="main">
    <div class="itemList">
      <% @items.each {|item| %>
        <div class="item">
          <div class="ranking">
            <%= item['ranking'] %>.
            <a href=<%= item['comment_link']%>><%= image_tag('grayarrow.gif') %></a>
          </div>
          <div class="content">
            <div class="upper">
              <a href=<%= item['url'] %>><%= item['title'] %></a> <span class="address"><a href=<%=item['host_search']%>><%= item['host'] %></a></span>
            </div>
            <div class="lower">
              <%= item['score'] %> by <a href=<%= item['by_link']%>><%= item['by'] %></a> <%= item['time'] %> ago | hide | <a href=<%= item['comment_link']%>><%=item['comment']%></a>
            </div>
          </div>
        </div>
      <% } %>
    </div>
    <div class="more">
      <%= link_to "More", item_index_path, id: "load-more"%>
    </div>
  </div>
  <div class="footer">
    <div class="application">
      <a href="https://www.ycombinator.com/apply/">Applications are open for YC Summer 2018</a>
    </div>
    <div class="links">
      <a href="https://news.ycombinator.com/newsguidelines.html">Guidelines</a> |
      <a href="https://news.ycombinator.com/newsfaq.html">FAQ</a> |
      <a href="mailto:hn@ycombinator.com">Support</a> |
      <a href="https://github.com/HackerNews/API">API</a> |
      <a href="https://news.ycombinator.com/security.html">Security</a> |
      <a href="https://news.ycombinator.com/lists">Lists</a> |
      <a href="https://news.ycombinator.com/bookmarklet.html">Bookmarklet</a> |
      <a href="https://news.ycombinator.com/dmca.html">DMCA</a> |
      <a href="http://www.ycombinator.com/apply/">Apply to YC</a> |
      <a href="mailto:hn@ycombinator.com">Contact</a>
    </div>
    <div class="search">
      <form>Search: <input type="text" value size="17"></form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneHackernews</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>